name: fastapi-mysql

services:   
  db-mysql:  #el servicio si quisiera usarlo deber√≠a cambiarlo a fastapi-db  
    image: mysql 
    container_name: db-mysql   
    environment:  
      MYSQL_ROOT_PASSWORD: quevedo
      MYSQL_DATABASE: seriesdb
      MYSQL_USER: quevedo
      MYSQL_PASSWORD: 1234
    ports:  
      - "3306:3306"  
